// 샘플 데이터셋 — MVP 데모·테스트용 실제 건물 레코드.
// 운영에서는 행안부 도로명주소 DB 전체분(수백만 건)을 Postgres 에 적재해 대체한다.
// (scripts/postal/load-juso.ts 참고)

import type { BuildingRecord } from "./types";

export const SAMPLE_RECORDS: BuildingRecord[] = [
  {
    zipcode: "06236",
    sido: "서울특별시",
    sigungu: "강남구",
    emd: "역삼동",
    ri: "",
    roadName: "테헤란로",
    buildingMain: 152,
    buildingSub: 0,
    isBasement: false,
    jibunMain: 737,
    jibunSub: 0,
    isMountain: false,
    buildingName: "강남파이낸스센터",
  },
  {
    zipcode: "06142",
    sido: "서울특별시",
    sigungu: "강남구",
    emd: "역삼동",
    ri: "",
    roadName: "테헤란로",
    buildingMain: 231,
    buildingSub: 0,
    isBasement: false,
    jibunMain: 706,
    jibunSub: 12,
    isMountain: false,
    buildingName: "",
  },
  {
    zipcode: "04524",
    sido: "서울특별시",
    sigungu: "중구",
    emd: "태평로1가",
    ri: "",
    roadName: "세종대로",
    buildingMain: 110,
    buildingSub: 0,
    isBasement: false,
    jibunMain: 31,
    jibunSub: 0,
    isMountain: false,
    buildingName: "서울특별시청",
  },
  {
    zipcode: "13561",
    sido: "경기도",
    sigungu: "성남시 분당구",
    emd: "정자동",
    ri: "",
    roadName: "불정로",
    buildingMain: 6,
    buildingSub: 0,
    isBasement: false,
    jibunMain: 178,
    jibunSub: 1,
    isMountain: false,
    buildingName: "그린팩토리",
  },
  {
    zipcode: "05551",
    sido: "서울특별시",
    sigungu: "송파구",
    emd: "신천동",
    ri: "",
    roadName: "올림픽로",
    buildingMain: 300,
    buildingSub: 0,
    isBasement: false,
    jibunMain: 29,
    jibunSub: 0,
    isMountain: false,
    buildingName: "롯데월드타워",
  },
  // 같은 우편번호에 복수 건물(1:N 데모용) — 06236 을 하나 더.
  {
    zipcode: "06236",
    sido: "서울특별시",
    sigungu: "강남구",
    emd: "역삼동",
    ri: "",
    roadName: "테헤란로",
    buildingMain: 142,
    buildingSub: 0,
    isBasement: false,
    jibunMain: 679,
    jibunSub: 5,
    isMountain: false,
    buildingName: "캡스톤타워",
  },
  {
    zipcode: "48058",
    sido: "부산광역시",
    sigungu: "해운대구",
    emd: "우동",
    ri: "",
    roadName: "센텀중앙로",
    buildingMain: 55,
    buildingSub: 0,
    isBasement: false,
    jibunMain: 1500,
    jibunSub: 8,
    isMountain: false,
    buildingName: "센텀리더스마크",
  },
  {
    zipcode: "61947",
    sido: "광주광역시",
    sigungu: "서구",
    emd: "치평동",
    ri: "",
    roadName: "상무중앙로",
    buildingMain: 80,
    buildingSub: 0,
    isBasement: false,
    jibunMain: 1213,
    jibunSub: 3,
    isMountain: false,
    buildingName: "",
  },
];
