import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // #region agent log
  if (typeof window === 'undefined') {
    fetch('http://127.0.0.1:7243/ingest/9e68326c-1d35-469f-95ce-dd5d2da86c08',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({location:'layout.tsx:27',message:'Server render: html lang="en"',data:{lang:'en',isServer:true},timestamp:Date.now(),sessionId:'debug-session',runId:'run1',hypothesisId:'A'})}).catch(()=>{});
  }
  // #endregion agent log
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* #region agent log */}
        {typeof window !== 'undefined' && (() => {
          const htmlEl = document.documentElement;
          fetch('http://127.0.0.1:7243/ingest/9e68326c-1d35-469f-95ce-dd5d2da86c08',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({location:'layout.tsx:35',message:'Client hydration: html attributes',data:{lang:htmlEl.getAttribute('lang'),className:htmlEl.className,isClient:true},timestamp:Date.now(),sessionId:'debug-session',runId:'run1',hypothesisId:'A'})}).catch(()=>{});
          return null;
        })()}
        {/* #endregion agent log */}
        <Header />
        {children}
      </body>
    </html>
  );
}
