/**
 * 16종 MBTI 성향 카드 사전 생성 스크립트 (일회성·재생성용)
 *
 * MBTI 경로는 입력이 16종(INTJ…ESFP)뿐이라, 같은 유형이면 AI 출력도 사실상 동일하다.
 * 미리 생성해 src/data/personalityCards.ts 에 캐싱하면 MBTI 경로는 라이브 AI 호출이 0건이 되어
 * 100명이 동시에 골라도 즉시·무료로 응답한다(무료 등급 분당 한도 RPM 폭주 회피).
 *
 * 실행:  npx tsx scripts/generate-personality-cards.ts
 * 재생성이 필요한 경우: 인물형 목록(bibleArchetypes)·프롬프트(ai.ts SYSTEM_INSTRUCTION/buildPersonalityPrompt)가 바뀔 때.
 *
 * ⚠️ 실제 생성 로직(parsePersonalityReport)을 그대로 재사용하므로 프롬프트/정규화가 100% 일치한다.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

// ── 1) .env.local 로드 (ai.ts가 import 시점에 GOOGLE_AI_API_KEY로 클라이언트를 만든다) ──
const envText = readFileSync(new URL("../.env.local", import.meta.url), "utf8");
for (const raw of envText.split(/\r?\n/)) {
  const line = raw.trim();
  if (!line || line.startsWith("#")) continue;
  const eq = line.indexOf("=");
  if (eq === -1) continue;
  const key = line.slice(0, eq).trim();
  let val = line.slice(eq + 1).trim();
  if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
    val = val.slice(1, -1);
  }
  if (!(key in process.env)) process.env[key] = val;
}

const TYPES = [
  "INTJ", "INTP", "ENTJ", "ENTP",
  "INFJ", "INFP", "ENFJ", "ENFP",
  "ISTJ", "ISFJ", "ESTJ", "ESFJ",
  "ISTP", "ISFP", "ESTP", "ESFP",
] as const;

// 생성 산출물 위에 덮어쓰는 큐레이션 보정 — 재생성해도 보존된다.
// AI 생성은 가끔 (a) catchphrase 머리말(핵심 명사) 누락 (b) 즉흥형(P)에 장기계획형 인물형을
// 대표로 배정하는 편차가 있어, 사람이 검수해 고친 항목만 여기 고정한다. (검토 워크플로 wf_e47eb3a5)
type CardField = "catchphrase" | "coreTraits" | "optimalEcosystem" | "corePosition";
const OVERRIDES: Record<string, Partial<Record<CardField, string>>> = {
  INTP: { catchphrase: "숨겨진 본질을 캐는 탐구자" }, // 머리말 없는 미완성 명사구 보정
  ESTP: { coreTraits: "에스더형, 바울형, 마르다형" },   // 대표를 장기계획형(느헤미야)→즉흥·위기대응형(에스더)으로
};

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

type GenFn = (type: string) => Promise<{ catchphrase: string; coreTraits: string; optimalEcosystem: string; corePosition: string }>;

async function generateOne(gen: GenFn, type: string) {
  // parsePersonalityReport는 내부적으로 모델 폴백(2.5-flash↔lite)으로 429를 흡수한다.
  // 그래도 드물게 전부 실패할 수 있으니 한 번 더 재시도.
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      return await gen(type);
    } catch (e) {
      if (attempt === 0) {
        console.warn(`  ↻ ${type} 재시도 (${e instanceof Error ? e.message.slice(0, 80) : e})`);
        await sleep(4000);
      } else {
        throw e;
      }
    }
  }
  throw new Error("unreachable");
}

async function main() {
  // env 세팅 후에 동적 import — 모듈 로드 시점에 GOOGLE_AI_API_KEY가 필요하기 때문
  const { parsePersonalityReport } = await import("../src/lib/ai.ts");

  const cards: Record<string, Record<CardField, string>> = {};
  for (const type of TYPES) {
    const card = await generateOne(parsePersonalityReport, type);
    cards[type] = card;
    console.log(`✓ ${type}  "${card.catchphrase}"  [${card.coreTraits}]`);
    await sleep(2500); // RPM에 여유를 주는 간격 (일회성이라 느려도 무방)
  }

  // 큐레이션 보정 적용 — 재생성해도 검수된 수정이 유지된다
  for (const [type, patch] of Object.entries(OVERRIDES)) {
    if (cards[type]) {
      cards[type] = { ...cards[type], ...patch };
      console.log(`✎ ${type} 보정 적용: ${Object.keys(patch).join(", ")}`);
    }
  }

  const entries = TYPES.map(
    (t) => `  ${JSON.stringify(t)}: ${JSON.stringify(cards[t], null, 2).replace(/\n/g, "\n  ")},`,
  ).join("\n");

  const file = `/**
 * AUTO-GENERATED by scripts/generate-personality-cards.ts — 손으로 수정하지 말 것.
 * (일부 항목은 생성기의 OVERRIDES로 큐레이션 보정됨 — 재생성해도 유지된다.)
 *
 * 16종 MBTI 성향 카드 사전 생성 캐시. MBTI 경로(기본 경로)는 입력이 16종뿐이라
 * 라이브 Gemini 호출 없이 이 캐시로 즉시 응답한다 → 동시 사용 폭주에도 무료·무한 처리.
 * 인물형/프롬프트가 바뀌면 재생성: npx tsx scripts/generate-personality-cards.ts
 */
import type { ParsedReport } from "@/lib/ai";

export const PERSONALITY_CARDS: Record<string, ParsedReport> = {
${entries}
};
`;

  const __dirname = dirname(fileURLToPath(import.meta.url));
  const outPath = `${__dirname}/../src/data/personalityCards.ts`;
  mkdirSync(`${__dirname}/../src/data`, { recursive: true });
  writeFileSync(outPath, file, "utf8");
  console.log(`\n📦 ${Object.keys(cards).length}종 생성 완료 → src/data/personalityCards.ts`);
}

main().catch((e) => {
  console.error("생성 실패:", e);
  process.exit(1);
});
